
POST http://localhost:5500/api/send-otp HTTP/1.1
Content-Type: application/json



#####

POST http://localhost:5500/api/verify-otp HTTP/1.1
Content-Type: application/json


#####
POST http://localhost:5500/api/encrypt HTTP/1.1
Content-Type: application/json

{
  "text": "hello"
}